// import "./globals.css";
"use client";


import Navbar from "@/app/components/Navbar";
// import Footer from "./components/Footer";
import { ChakraProvider } from "@chakra-ui/react";
import { store } from "./store";
import { Provider } from "react-redux";

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Provider store={store}>
            <ChakraProvider>
                <div className="">
                    <body className={``}>
                        <Navbar />
                        <div className="border border-red-500 !bg-zinc-100">
                            {children}
                        </div>
                        {/*<Footer />*/}
                    </body>
                </div>
            </ChakraProvider>
            </Provider>
        </html>
    );
}
