// import "./globals.css";
"use client";

import { Analytics } from "@vercel/analytics/react";
import Navbar from "@/app/components/Navbar";
// import Footer from "./components/Footer";
import { Box, ChakraProvider } from "@chakra-ui/react";
import { store } from "./store";
import { Provider } from "react-redux";

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Provider store={store}>
        <ChakraProvider>
          <Analytics />
          <body>
            <Navbar />
            <Box pt="60px" bgColor="gray.100">
              {children}
            </Box>
          </body>
        </ChakraProvider>
      </Provider>
    </html>
  );
}
